name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages-${{ github.run_id }}
          path: ./build

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GH_PAT }} 
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: github-pages-${{ github.run_id }}
          preview: false
